### ISSUE TITLE
Proposal: change the work with the module to the configuration in yaml files

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#14]
As preliminary testing has shown, working with configuration exclusively through console input is not flexible and does not provide portability.

This approach also greatly complicates development and maintenance, which does not meet the original goals and objectives of this project: to provide a simple and reliable tool for building distributions.

The current approach also poorly supports CI/CD, due to the lack of centralized configuration for build systems.

Given these facts, it is better to replace the assembly configuration with yaml files, the closest example is Helm charts.

For example, in its simplest form it could be something like this:

```yaml
name: test
version: 1.0.0
account: test
repository: ""
buildDirectory: "./dist"
logDirectory: "./logs"
mapping:
  - name: "xxx"
    relativePath: "install/components"
    paths:
      - ./bitrix/components
      - ./local/components
  - name: "xxx"
    relativePath: "install/templates"
    paths:
      - ./bitrix/templates
      - ./local/templates
ignore:
  - "**/*.log"
```

This approach, in addition to the obvious convenience of working with modules, also solves the problem of storing confidential account data.

To implement this task, we will have to completely revise the current code base and rewrite the project, but it is clearly worth it.
