### ISSUE TITLE
Add support for commit message transformations (`transform` field)

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#177]
We plan to introduce a new configuration field called `transform` that allows modifying commit messages before rendering the changelog.

The first supported transformation type will be `stripPrefix`, which removes defined prefixes from commit messages (e.g. `feat:`, `fix:`). This will help improve readability of generated changelogs.

The `transform` field is designed to be extensible, so additional transformation types like `stripSuffix`, `replace`, and `regexReplace` can be added in the future.

## Example configuration

```yaml
transform:
  - type: "stripPrefix"
    value:
      - "feat:"
      - "fix:"
```

This feature will be applied after filtering commits by pattern, but before rendering them in the changelog.
