### ISSUE TITLE
Proposal: Template for Extensible Callbacks in Build Stages

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#21]
## Structure of the Callback Template  

We define the callback mechanism as a set of actions that can be extended with custom logic. Instead of executing just shell scripts, the callback can accept different types of logic, such as functions, external tools, or even API calls. The core idea is to create a flexible structure where each callback can be configured with specific parameters to fit different use cases.

## Example Configuration  

```yaml
callbacks:
  - stage: "components"
    preStage:
      type: "script"  # Executes an external script
      action: "./scripts/pre_components.sh"  # Path to the script
      parameters:
        - "--force"
        - "--verbose"
    postStage:
      type: "external"  # Calls an external API
      action: "http://example.com/api/complete"  # API endpoint
      method: "POST"  # HTTP method (GET, POST, PUT, DELETE, etc.)
      parameters:
        - "auth_token=xyz123"
        - "stage=components"

  - stage: "templates"
    preStage:
      type: "script"  # Executes an external script
      action: "./scripts/pre_templates.sh"  # Path to the script
      parameters:
        - "--prepare"
    postStage:
      type: "external"  # Calls an external API
      action: "http://example.com/api/notify"  # API endpoint
      method: "GET"  # HTTP method (GET, POST, PUT, DELETE, etc.)
      parameters:
        - "auth_token=xyz456"
        - "status=done"

global:
  preBuild:
    type: "script"
    action: "./scripts/initialize.sh"  # Runs a script before the entire build
    parameters:
      - "--init"
  postBuild:
    type: "external"
    action: "http://example.com/api/finalize"  # API endpoint after build completes
    method: "PUT"  # HTTP method (GET, POST, PUT, DELETE, etc.)
    parameters:
      - "auth_token=xyz789"
      - "build_status=success"
```

## Types of Callbacks

- **script**: Executes an external script with specified arguments.
- **external**: Calls an external API or service, triggering a remote action.

## Expected Behavior

- Each stage can have `preStage` and `postStage` actions with different types of logic.
- `global preBuild` and `postBuild` callbacks work before and after the entire build process, respectively.
- Each callback can receive parameters that modify its behavior.
- Callback types (`script`, `external`) are extensible — new types can be added easily.

## Benefits of This Template

- **Flexibility**: Supports different types of logic (scripts, external API calls), making it adaptable to various use cases.
- **Extensibility**: New callback types can be added in the future (e.g., event listeners, condition-based triggers, etc.).
- **Seamless Integration**: Callbacks can be written in various languages or technologies (e.g., shell scripts, API calls).
- **Customizability**: Easily tweak parameters to fit specific requirements of different stages or the entire build process.

## Example Extensions

- **Custom Functions**: Write custom logic for pre/post processing directly in the build configuration or in the codebase.
- **Plugin Support**: Add support for third-party plugins that perform additional actions (e.g., sending notifications, interacting with cloud services, etc.).
- **Event-Driven Triggers**: Allow callbacks to be triggered based on specific events (e.g., file changes, version tags).
