### ISSUE TITLE
Feature Request: Automatic Changelog Generation Based on Configuration

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#73]
**Description:**

I propose extending the build system functionality by adding the ability to automatically generate a changelog. This enhancement would simplify the release process and automatically create a clear, structured changelog based on specified criteria.

**Proposed configuration extension:**

```yaml
changelog:
  from:
    type: "tag" # Allowed values: "tag", "commit"
    value: "v1.0.0"
  to:
    type: "tag" # Allowed values: "tag", "commit"
    value: "v2.0.0"
  condition:
    type: "include" # Allowed values: "include", "exclude"
    value: # Array of regular expressions for commit filtering
      - "^feat:([\W\w]+)$"
      - "^fix:([\W\w]+)$"
```

**Field descriptions:**

- `from` and `to` specify the range of versions (git tags or specific commits) from which changes will be collected. The `type` field can only have two values: `tag` or `commit`.
- The `condition` field defines the criteria for including commits in the final changelog. The `type` field can only have two values: `include` (include only matching commits) or `exclude` (exclude matching commits). The `value` field is an array of regular expressions used to filter commits. In the example above, commits matching patterns with prefixes `feat:` and `fix:` will be included.

**Implementation Goals:**

- Simplify and automate the creation of release notes.
- Improve transparency of changes between releases.
- Establish a unified standard for changelog generation.
