### ISSUE TITLE
Add Build Parameters for Stage Composition

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#76]
## Description
Propose adding a new configuration section to support build parameters that allow the composition of stages using lists. This feature will enable users to define custom build pipelines (e.g., for release builds or last version updates) without duplicating stage definitions.

## Benefits
- **Flexibility:** Define multiple build pipelines by combining different stages.
- **Modularity:** Reuse stage definitions across various build scenarios.
- **Clarity:** Enhance readability and maintainability of the configuration file.

## Proposed Changes
Introduce a new `build` section in the configuration file with the following structure:

```yaml
build:
  release:
    - stage_1
    - stage_2
  lastVersion:
    - stage_3
```
