### ISSUE TITLE
Feature Request: Add filter Option to Stages for Selective File Copying

### ISSUE THREAD

**Issue by pixel365** [pixel365/bx#89]
**Description:**

Currently, the `stages` section allows defining file copying operations but lacks fine-grained control over which files to include beyond `ignore`, which operates globally. To improve flexibility, I propose adding a `filter` option to each stage, enabling selective copying of files based on patterns.

**Proposed Configuration:**

```yaml
stages:
  - name: "components"
    to: "{install}/components"
    actionIfFileExists: "replace"
    from:
      - "{bitrix}/components"
      - "{local}/components"
    filter:
      - "**/*.php"   # Copy only PHP files
      - "!*_test.php" # Exclude files ending with _test.php
```

**Functionality:**
- If `filter` is **not specified**, all files are copied (default behavior).
- If `filter` **is specified**, only files matching at least one pattern will be copied.
- **Negative patterns (`!pattern`)** can be used to exclude specific files within the `filter` scope.
- The `filter` applies **only within the `from` paths** of a given stage.

**Use Cases:**
- Allow copying only `.php` files while excluding documentation or config files.
- Exclude test files (`*_test.php`) but include everything else.
- Copy only assets like `.css` or `.js` from specific directories.

**Implementation Considerations:**
- The behavior should be similar to `ignore`, but applied at the **stage level** rather than globally.
- Ensure wildcard patterns (`**`, `*`, `?`) are supported.
- Ensure negative rules (`!pattern`) override positive rules where applicable.
